// mod_unaquire,prc_onunaquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_unaquire", OBJECT_SELF);
    ExecuteScript("prc_onunaquire", OBJECT_SELF);
}
