// mod_exit,prc_onleave
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onclientleave event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_exit", OBJECT_SELF);
    ExecuteScript("prc_onleave", OBJECT_SELF);
}
