// mod_hb,prc_onheartbeat
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onheartbeat event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_hb", OBJECT_SELF);
    ExecuteScript("prc_onheartbeat", OBJECT_SELF);
}
