// mod_ud,prc_onuserdef
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onuserdefined event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_ud", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_onuserdef", OBJECT_SELF);
}
