// mod_unequip,prc_unequip
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerunequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_unequip", OBJECT_SELF);
    ExecuteScript("prc_unequip", OBJECT_SELF);
}
