// mod_rest,prc_rest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_rest", OBJECT_SELF);
    ExecuteScript("prc_rest", OBJECT_SELF);
}
