// mod_respawn,prc_onrespawn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_respawn", OBJECT_SELF);
    ExecuteScript("prc_onrespawn", OBJECT_SELF);
}
