// mod_death,prc_ondeath
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdeath event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_death", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_ondeath", OBJECT_SELF);
}
