// mod_level,prc_levelup
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerlevelup event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_level", OBJECT_SELF);
    ExecuteScript("prc_levelup", OBJECT_SELF);
}
