// mod_unaquire,prc_onunaquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_unaquire", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_onunaquire", OBJECT_SELF);
}
