// mod_cut_abort,prc_oncutabort
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncutsceneabort event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_cut_abort", OBJECT_SELF);
    ExecuteScript("prc_oncutabort", OBJECT_SELF);
}
