// mod_ud,prc_onuserdef
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onuserdefined event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_ud", OBJECT_SELF);
    ExecuteScript("prc_onuserdef", OBJECT_SELF);
}
