// mod_aquire,prc_onaquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onacquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_aquire", OBJECT_SELF);
    ExecuteScript("prc_onaquire", OBJECT_SELF);
}
