// mod_enter,prc_onenter
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncliententer event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_enter", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_onenter", OBJECT_SELF);
}
