// mod_exit,prc_onleave
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onclientleave event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_exit", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_onleave", OBJECT_SELF);
}
