// mod_enter,prc_onenter
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncliententer event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_enter", OBJECT_SELF);
    ExecuteScript("prc_onenter", OBJECT_SELF);
}
