// mod_load,prc_onmodload
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onmoduleload event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_load", OBJECT_SELF);
    ExecuteScript("prc_onmodload", OBJECT_SELF);
}
