// mod_unequip,prc_unequip
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerunequipitem event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_unequip", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_unequip", OBJECT_SELF);
}
