// mod_level,prc_levelup
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerlevelup event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_level", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_levelup", OBJECT_SELF);
}
