// mod_respawn,prc_onrespawn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_respawn", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_onrespawn", OBJECT_SELF);
}
