// mod_rest,prc_rest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_rest", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_rest", OBJECT_SELF);
}
