// mod_activate,prc_onactivate
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onactivateitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_activate", OBJECT_SELF);
    ExecuteScript("prc_onactivate", OBJECT_SELF);
}
