// mod_equip,prc_equip
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_equip", OBJECT_SELF);
    ExecuteScript("prc_equip", OBJECT_SELF);
}
