// mod_cut_abort,prc_oncutabort
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncutsceneabort event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_cut_abort", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_oncutabort", OBJECT_SELF);
}
