// mod_death,prc_ondeath
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdeath event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("mod_death", OBJECT_SELF);
    ExecuteScript("prc_ondeath", OBJECT_SELF);
}
