// mod_dying,prc_ondying
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdying event.
//
/////////////////////////////////////////////////////////////////////

#include "prc_gateway"

void main()
{
    ExecuteScript("mod_dying", OBJECT_SELF);
    if(!PRC_EVENT_DISABLE)
        ExecuteScript("prc_ondying", OBJECT_SELF);
}
