/** @file inc_switch_setup
    Functions for switch setups. Most only used on
    mod load. Get/Set individual switches is done
    via prc_inc_switch.
    DO NOT include this file if you just want to
    use Set/GetPRCSwitch as it's not needed.
*/

//////////////////////////////////////////////////
/*             Function prototypes              */
//////////////////////////////////////////////////

/**
 * Controls which itemproperties can be added to
 * the samurai weapon.
 * @see PRC_SAMURAI_BAN_ in prc_inc_switch and the
 * function difinition for more info.
 */
void DoSamuraiBanDefaults();

/**
 * Sets the epic spell switches to their default values.
 *
 * If PRC_EPIC_INGORE_DEFAULTS is set, this does nothing.
 */
void DoEpicSpellDefaults();

/**
 * Sets the file end markers to their default values.
 *
 * If FILE_END_MANUAL is set, this does nothing.
 */
void SetDefaultFileEnds();

/**
 * This creates an array of all switch names on a waypoint
 * It is used for the switch setting convo to loop over switches easily
 */
void CreateSwitchNameArray();

//////////////////////////////////////////////////
/* Include section                              */
//////////////////////////////////////////////////

#include "inc_array" // Needs direct include instead of inc_utility
#include "prc_inc_switch"

//////////////////////////////////////////////////
/*             Function definitions             */
//////////////////////////////////////////////////

void DoSamuraiBanDefaults()
{
    if(GetPRCSwitch(PRC_SAMURAI_DISABLE_DEFAULT_BAN))
        return;
    //remove all penalty iprops
    SetPRCSwitch(PRC_SAMURAI_BAN_+"10_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"21_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"24_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"27_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"28_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"29_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"47_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"49_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"50_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"60_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"62_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"63_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"64_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"65_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"66_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"81_*_*_*", TRUE);
    //PRCs restrictions
    SetPRCSwitch(PRC_SAMURAI_BAN_+"86_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"87_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"88_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"89_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"90_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"91_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"120_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"121_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"122_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"123_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"124_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"125_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"126_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"127_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"134_*_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"150_*_*_*", TRUE);
    //only allow elemental damages 6,7,9,10,13
    //damage
    SetPRCSwitch(PRC_SAMURAI_BAN_+"16_5_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"16_8_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"16_11_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"16_12_*_*", TRUE);
    //damage vs race
    SetPRCSwitch(PRC_SAMURAI_BAN_+"17_*_5_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"17_*_8_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"17_*_11_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"17_*_12_*", TRUE);
    //damage vs alignment
    SetPRCSwitch(PRC_SAMURAI_BAN_+"18_*_5_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"18_*_8_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"18_*_11_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"18_*_12_*", TRUE);
    //damage vs specific alignment
    SetPRCSwitch(PRC_SAMURAI_BAN_+"19_*_5_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"19_*_8_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"19_*_11_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"19_*_12_*", TRUE);
    //damage immunity
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_5_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_8_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_11_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_12_*_*", TRUE);
    //damage resist
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_5_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_8_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_11_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"20_12_*_*", TRUE);
    //slays
    SetPRCSwitch(PRC_SAMURAI_BAN_+"48_21_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"48_22_*_*", TRUE);
    SetPRCSwitch(PRC_SAMURAI_BAN_+"48_23_*_*", TRUE);
    //vorpal
    SetPRCSwitch(PRC_SAMURAI_BAN_+"48_24_*_*", TRUE);
}

void DoEpicSpellDefaults()
{
    if(GetPRCSwitch(PRC_EPIC_INGORE_DEFAULTS))
        return;
    SetPRCSwitch(PRC_EPIC_XP_COSTS, TRUE);
    SetPRCSwitch(PRC_EPIC_BACKLASH_DAMAGE, TRUE);
    SetPRCSwitch(PRC_EPIC_FOCI_ADJUST_DC, TRUE);
    SetPRCSwitch(PRC_EPIC_GOLD_MULTIPLIER, 9000);
    SetPRCSwitch(PRC_EPIC_XP_FRACTION, 25);
    SetPRCSwitch(PRC_EPIC_FAILURE_FRACTION_GOLD, 2);
    SetPRCSwitch(PRC_EPIC_BOOK_DESTRUCTION, 50);
}

void SetDefaultFileEnds()
{
    // Overridden values: (TMI prevention)
    //
    // feat.2da - 390
    // spells.2da - 539

    //START AUTO-GENERATED FILEENDS
    SetPRCSwitch("PRC_FILE_END_baseitems", 204);
    SetPRCSwitch("PRC_FILE_END_classes", 254);
    SetPRCSwitch("PRC_FILE_END_cls_atk_4", 59);
    SetPRCSwitch("PRC_FILE_END_cls_atk_5", 59);
    SetPRCSwitch("PRC_FILE_END_cls_atk_adst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_adst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_alag", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_alienist", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_aots", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_arch", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_arclb", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_arctrk", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_arti", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_baal", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bereft", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bfz", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_blades", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_blarch", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bldclw", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_blmagu", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bltl", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bonded", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_bowman", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_brage", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_brawl", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_brimst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_cbtmed", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_cereb", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_cntmp", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_coc", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_crusdr", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_cwsm", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dalqur", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_deepst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dfa", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_diabol", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_diadra", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dirge", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_disp", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dnecro", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_doa", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dradev", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_dradis", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_drgnht", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_drgshm", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_drnkn", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_drowj", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_drslyr", 49);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_duel", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_duskbl", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_eldkni", 58);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_enlfis", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_eog", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_etbl", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_favsol", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_fh", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_fistra", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_fom", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_foz", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_frebzk", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_gfkill", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hath", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_havocm", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_healer", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_heartw", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hexbl", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hextor", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hiero", 4);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hmage", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hnshn", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hosp", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_hotwm", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_iaij", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_irnmnd", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_jpm", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_justww", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_kchal", 10);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_knight", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_kord", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_kotmc", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_lasher", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_lgdr", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_lich", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_maestr", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_magek", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_manat", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_marsh", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_meph", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_mharp", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_minstr", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_monine", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_mos", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_mstalc", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_myst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_mystic", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ninjca", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_noble", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ocu", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ollam", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ootbi", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ooze", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_orcus", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_orcwar", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_parch", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_pdk", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_psion", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_psych", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_psywar", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_rava", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_rbyknt", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_redav", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_redwiz", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_rune", 60);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_runec", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sacfis", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_samur", 58);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_savant", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sbheir", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_schord", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_scout", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sdmind", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_shaman", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_shdbld", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_shou", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_shugen", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sklcln", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sleat", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sncmnd", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sod", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sohei", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_sol", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_soulkn", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_spellf", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_spells", 58);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_ssn", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_storml", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_suel", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_swash", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_swdsge", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_swftwg", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_taltia", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_tempst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_tempus", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_tfshad", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_thaykt", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_thrall", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_tnecro", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_tog", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_true", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_urang", 58);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_vassal", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_vigil", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_virt", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_warbld", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_warchf", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wardrk", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_warlok", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_warmnd", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wilder", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wrmage", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wrslng", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wwoc", 59);
    SetPRCSwitch("PRC_FILE_END_cls_bfeat_wwolf", 59);
    SetPRCSwitch("PRC_FILE_END_cls_feat_aber", 349);
    SetPRCSwitch("PRC_FILE_END_cls_feat_adst", 12);
    SetPRCSwitch("PRC_FILE_END_cls_feat_alag", 222);
    SetPRCSwitch("PRC_FILE_END_cls_feat_alienist", 36);
    SetPRCSwitch("PRC_FILE_END_cls_feat_antipl", 721);
    SetPRCSwitch("PRC_FILE_END_cls_feat_aots", 126);
    SetPRCSwitch("PRC_FILE_END_cls_feat_arch", 36);
    SetPRCSwitch("PRC_FILE_END_cls_feat_arclb", 389);
    SetPRCSwitch("PRC_FILE_END_cls_feat_arctrk", 97);
    SetPRCSwitch("PRC_FILE_END_cls_feat_arti", 430);
    SetPRCSwitch("PRC_FILE_END_cls_feat_asasin", 203);
    SetPRCSwitch("PRC_FILE_END_cls_feat_baal", 18);
    SetPRCSwitch("PRC_FILE_END_cls_feat_baeln", 22);
    SetPRCSwitch("PRC_FILE_END_cls_feat_barb", 467);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bard", 1015);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bereft", 4);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bfz", 28);
    SetPRCSwitch("PRC_FILE_END_cls_feat_blades", 143);
    SetPRCSwitch("PRC_FILE_END_cls_feat_blarch", 14);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bldclw", 13);
    SetPRCSwitch("PRC_FILE_END_cls_feat_blkgrd", 354);
    SetPRCSwitch("PRC_FILE_END_cls_feat_blmagus", 32);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bltl", 11);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bonded", 44);
    SetPRCSwitch("PRC_FILE_END_cls_feat_bowman", 331);
    SetPRCSwitch("PRC_FILE_END_cls_feat_brage", 180);
    SetPRCSwitch("PRC_FILE_END_cls_feat_brawl", 612);
    SetPRCSwitch("PRC_FILE_END_cls_feat_brimst", 5);
    SetPRCSwitch("PRC_FILE_END_cls_feat_cbtmed", 7);
    SetPRCSwitch("PRC_FILE_END_cls_feat_cereb", 212);
    SetPRCSwitch("PRC_FILE_END_cls_feat_chaban", 362);
    SetPRCSwitch("PRC_FILE_END_cls_feat_cler", 801);
    SetPRCSwitch("PRC_FILE_END_cls_feat_cntmp", 52);
    SetPRCSwitch("PRC_FILE_END_cls_feat_coc", 214);
    SetPRCSwitch("PRC_FILE_END_cls_feat_corup", 510);
    SetPRCSwitch("PRC_FILE_END_cls_feat_crea", 443);
    SetPRCSwitch("PRC_FILE_END_cls_feat_crusdr", 389);
    SetPRCSwitch("PRC_FILE_END_cls_feat_cwsm", 654);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dalqur", 184);
    SetPRCSwitch("PRC_FILE_END_cls_feat_deepst", 9);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dfa", 362);
    SetPRCSwitch("PRC_FILE_END_cls_feat_diabol", 114);
    SetPRCSwitch("PRC_FILE_END_cls_feat_diadra", 22);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dirge", 4);
    SetPRCSwitch("PRC_FILE_END_cls_feat_disp", 18);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dnecro", 1116);
    SetPRCSwitch("PRC_FILE_END_cls_feat_doa", 11);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dradev", 364);
    SetPRCSwitch("PRC_FILE_END_cls_feat_dradis", 150);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drag", 441);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drgnht", 79);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drgshm", 419);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drnkn", 15);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drowj", 42);
    SetPRCSwitch("PRC_FILE_END_cls_feat_drslyr", 222);
    SetPRCSwitch("PRC_FILE_END_cls_feat_druid", 790);
    SetPRCSwitch("PRC_FILE_END_cls_feat_duel", 65);
    SetPRCSwitch("PRC_FILE_END_cls_feat_duskbl", 749);
    SetPRCSwitch("PRC_FILE_END_cls_feat_eldkni", 299);
    SetPRCSwitch("PRC_FILE_END_cls_feat_enlfis", 165);
    SetPRCSwitch("PRC_FILE_END_cls_feat_eog", 13);
    SetPRCSwitch("PRC_FILE_END_cls_feat_etbl", 12);
    SetPRCSwitch("PRC_FILE_END_cls_feat_favsol", 1627);
    SetPRCSwitch("PRC_FILE_END_cls_feat_fh", 31);
    SetPRCSwitch("PRC_FILE_END_cls_feat_fight", 661);
    SetPRCSwitch("PRC_FILE_END_cls_feat_fistra", 344);
    SetPRCSwitch("PRC_FILE_END_cls_feat_fom", 34);
    SetPRCSwitch("PRC_FILE_END_cls_feat_foz", 257);
    SetPRCSwitch("PRC_FILE_END_cls_feat_frebzk", 22);
    SetPRCSwitch("PRC_FILE_END_cls_feat_gfkill", 26);
    SetPRCSwitch("PRC_FILE_END_cls_feat_gian", 442);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hath", 77);
    SetPRCSwitch("PRC_FILE_END_cls_feat_havocm", 0);
    SetPRCSwitch("PRC_FILE_END_cls_feat_healer", 783);
    SetPRCSwitch("PRC_FILE_END_cls_feat_heartw", 105);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hexbl", 583);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hextor", 204);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hiero", 41);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hmage", 76);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hnshn", 30);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hosp", 316);
    SetPRCSwitch("PRC_FILE_END_cls_feat_hotwm", 17);
    SetPRCSwitch("PRC_FILE_END_cls_feat_iaij", 202);
    SetPRCSwitch("PRC_FILE_END_cls_feat_inidra", 115);
    SetPRCSwitch("PRC_FILE_END_cls_feat_irnmnd", 10);
    SetPRCSwitch("PRC_FILE_END_cls_feat_jpm", 8);
    SetPRCSwitch("PRC_FILE_END_cls_feat_justww", 79);
    SetPRCSwitch("PRC_FILE_END_cls_feat_kchal", 175);
    SetPRCSwitch("PRC_FILE_END_cls_feat_knight", 316);
    SetPRCSwitch("PRC_FILE_END_cls_feat_kord", 3);
    SetPRCSwitch("PRC_FILE_END_cls_feat_kotmc", 249);
    SetPRCSwitch("PRC_FILE_END_cls_feat_lasher", 368);
    SetPRCSwitch("PRC_FILE_END_cls_feat_lgdr", 214);
    SetPRCSwitch("PRC_FILE_END_cls_feat_lich", 26);
    SetPRCSwitch("PRC_FILE_END_cls_feat_maestr", 10);
    SetPRCSwitch("PRC_FILE_END_cls_feat_magek", 138);
    SetPRCSwitch("PRC_FILE_END_cls_feat_manat", 252);
    SetPRCSwitch("PRC_FILE_END_cls_feat_marsh", 489);
    SetPRCSwitch("PRC_FILE_END_cls_feat_meph", 21);
    SetPRCSwitch("PRC_FILE_END_cls_feat_mharp", 173);
    SetPRCSwitch("PRC_FILE_END_cls_feat_minstr", 42);
    SetPRCSwitch("PRC_FILE_END_cls_feat_monine", 7);
    SetPRCSwitch("PRC_FILE_END_cls_feat_monk", 414);
    SetPRCSwitch("PRC_FILE_END_cls_feat_mos", 83);
    SetPRCSwitch("PRC_FILE_END_cls_feat_mstalc", 10);
    SetPRCSwitch("PRC_FILE_END_cls_feat_myst", 1665);
    SetPRCSwitch("PRC_FILE_END_cls_feat_mystic", 108);
    SetPRCSwitch("PRC_FILE_END_cls_feat_nights", 64);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ninja", 71);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ninjca", 370);
    SetPRCSwitch("PRC_FILE_END_cls_feat_noble", 413);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ocu", 674);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ollam", 2);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ootbi", 40);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ooze", 40);
    SetPRCSwitch("PRC_FILE_END_cls_feat_orcus", 38);
    SetPRCSwitch("PRC_FILE_END_cls_feat_orcwar", 8);
    SetPRCSwitch("PRC_FILE_END_cls_feat_outs", 2160);
    SetPRCSwitch("PRC_FILE_END_cls_feat_pal", 513);
    SetPRCSwitch("PRC_FILE_END_cls_feat_palema", 83);
    SetPRCSwitch("PRC_FILE_END_cls_feat_parch", 18);
    SetPRCSwitch("PRC_FILE_END_cls_feat_pdk", 10);
    SetPRCSwitch("PRC_FILE_END_cls_feat_pnpsfr", 140);
    SetPRCSwitch("PRC_FILE_END_cls_feat_psion", 963);
    SetPRCSwitch("PRC_FILE_END_cls_feat_psych", 212);
    SetPRCSwitch("PRC_FILE_END_cls_feat_psywar", 684);
    SetPRCSwitch("PRC_FILE_END_cls_feat_pyro", 293);
    SetPRCSwitch("PRC_FILE_END_cls_feat_rang", 423);
    SetPRCSwitch("PRC_FILE_END_cls_feat_rava", 210);
    SetPRCSwitch("PRC_FILE_END_cls_feat_rbyknt", 7);
    SetPRCSwitch("PRC_FILE_END_cls_feat_redav", 141);
    SetPRCSwitch("PRC_FILE_END_cls_feat_redwiz", 192);
    SetPRCSwitch("PRC_FILE_END_cls_feat_rog", 382);
    SetPRCSwitch("PRC_FILE_END_cls_feat_rune", 19);
    SetPRCSwitch("PRC_FILE_END_cls_feat_runec", 33);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sacfis", 173);
    SetPRCSwitch("PRC_FILE_END_cls_feat_samur", 678);
    SetPRCSwitch("PRC_FILE_END_cls_feat_savanta", 89);
    SetPRCSwitch("PRC_FILE_END_cls_feat_savantc", 89);
    SetPRCSwitch("PRC_FILE_END_cls_feat_savante", 89);
    SetPRCSwitch("PRC_FILE_END_cls_feat_savantf", 89);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sbheir", 203);
    SetPRCSwitch("PRC_FILE_END_cls_feat_schord", 1002);
    SetPRCSwitch("PRC_FILE_END_cls_feat_scout", 514);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sdmind", 186);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shadep", 106);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shadow", 57);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shaman", 941);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shdbld", 11);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shou", 59);
    SetPRCSwitch("PRC_FILE_END_cls_feat_shugen", 566);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sklcln", 7);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sleat", 4);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sncmnd", 5);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sod", 65);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sohei", 641);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sol", 329);
    SetPRCSwitch("PRC_FILE_END_cls_feat_sorc", 2635);
    SetPRCSwitch("PRC_FILE_END_cls_feat_soulkn", 761);
    SetPRCSwitch("PRC_FILE_END_cls_feat_spellf", 14);
    SetPRCSwitch("PRC_FILE_END_cls_feat_spells", 493);
    SetPRCSwitch("PRC_FILE_END_cls_feat_ssn", 16);
    SetPRCSwitch("PRC_FILE_END_cls_feat_storml", 102);
    SetPRCSwitch("PRC_FILE_END_cls_feat_suel", 470);
    SetPRCSwitch("PRC_FILE_END_cls_feat_swash", 587);
    SetPRCSwitch("PRC_FILE_END_cls_feat_swdsge", 471);
    SetPRCSwitch("PRC_FILE_END_cls_feat_swftwg", 29);
    SetPRCSwitch("PRC_FILE_END_cls_feat_taltia", 18);
    SetPRCSwitch("PRC_FILE_END_cls_feat_tempst", 143);
    SetPRCSwitch("PRC_FILE_END_cls_feat_tempus", 84);
    SetPRCSwitch("PRC_FILE_END_cls_feat_tfshad", 98);
    SetPRCSwitch("PRC_FILE_END_cls_feat_thaykt", 115);
    SetPRCSwitch("PRC_FILE_END_cls_feat_thrall", 187);
    SetPRCSwitch("PRC_FILE_END_cls_feat_tnecro", 87);
    SetPRCSwitch("PRC_FILE_END_cls_feat_tog", 113);
    SetPRCSwitch("PRC_FILE_END_cls_feat_true", 432);
    SetPRCSwitch("PRC_FILE_END_cls_feat_urang", 557);
    SetPRCSwitch("PRC_FILE_END_cls_feat_vassal", 409);
    SetPRCSwitch("PRC_FILE_END_cls_feat_vigil", 160);
    SetPRCSwitch("PRC_FILE_END_cls_feat_virt", 122);
    SetPRCSwitch("PRC_FILE_END_cls_feat_warbld", 443);
    SetPRCSwitch("PRC_FILE_END_cls_feat_warchf", 111);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wardark", 19);
    SetPRCSwitch("PRC_FILE_END_cls_feat_warlok", 512);
    SetPRCSwitch("PRC_FILE_END_cls_feat_warmnd", 390);
    SetPRCSwitch("PRC_FILE_END_cls_feat_warpr", 67);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wilder", 972);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wiz", 796);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wm", 178);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wrmage", 1200);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wrslng", 2);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wwoc", 23);
    SetPRCSwitch("PRC_FILE_END_cls_feat_wwolf", 20);
    SetPRCSwitch("PRC_FILE_END_cls_invkn_dfa", 59);
    SetPRCSwitch("PRC_FILE_END_cls_invkn_warlok", 59);
    SetPRCSwitch("PRC_FILE_END_cls_inv_dfa", 43);
    SetPRCSwitch("PRC_FILE_END_cls_inv_warlok", 112);
    SetPRCSwitch("PRC_FILE_END_cls_ivcr_dfa", 22);
    SetPRCSwitch("PRC_FILE_END_cls_ivcr_warlok", 93);
    SetPRCSwitch("PRC_FILE_END_cls_move_crusdr", 73);
    SetPRCSwitch("PRC_FILE_END_cls_move_swdsge", 141);
    SetPRCSwitch("PRC_FILE_END_cls_move_warbld", 110);
    SetPRCSwitch("PRC_FILE_END_cls_mvcr_crusdr", 69);
    SetPRCSwitch("PRC_FILE_END_cls_mvcr_swdsge", 140);
    SetPRCSwitch("PRC_FILE_END_cls_mvcr_warbld", 109);
    SetPRCSwitch("PRC_FILE_END_cls_mvkn_crusdr", 59);
    SetPRCSwitch("PRC_FILE_END_cls_mvkn_swdsge", 59);
    SetPRCSwitch("PRC_FILE_END_cls_mvkn_warbld", 59);
    SetPRCSwitch("PRC_FILE_END_cls_pres_aber", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_adst", 11);
    SetPRCSwitch("PRC_FILE_END_cls_pres_alag", 18);
    SetPRCSwitch("PRC_FILE_END_cls_pres_alienist", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ani", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_antipl", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_aots", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_arch", 12);
    SetPRCSwitch("PRC_FILE_END_cls_pres_archer", 22);
    SetPRCSwitch("PRC_FILE_END_cls_pres_archr", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_arctrk", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_arti", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_baal", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_baeln", 18);
    SetPRCSwitch("PRC_FILE_END_cls_pres_barb", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bard", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_beast", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bereft", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bfz", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_blades", 29);
    SetPRCSwitch("PRC_FILE_END_cls_pres_blarch", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bldclw", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_blmagus", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bltl", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bonded", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_bowman", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_brage", 14);
    SetPRCSwitch("PRC_FILE_END_cls_pres_brawl", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_brimst", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_cbtmed", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_cereb", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_chaban", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_cler", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_cntmp", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_coc", 30);
    SetPRCSwitch("PRC_FILE_END_cls_pres_con", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_corup", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_crusdr", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_cwsm", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dalqur", 37);
    SetPRCSwitch("PRC_FILE_END_cls_pres_deepst", 11);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dfa", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_diabol", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_diadra", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dirge", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_disp", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_divsav", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dnecro", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_doa", 10);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dradev", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dradis", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_drag", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_drgnht", 23);
    SetPRCSwitch("PRC_FILE_END_cls_pres_drgshm", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_drnkn", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_drowj", 10);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dru", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dslyr", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_duel", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_duskbl", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_dwdef", 14);
    SetPRCSwitch("PRC_FILE_END_cls_pres_eldkni", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ele", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_enlfis", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_eog", 12);
    SetPRCSwitch("PRC_FILE_END_cls_pres_etbl", 16);
    SetPRCSwitch("PRC_FILE_END_cls_pres_favsol", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_fey", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_fh", 44);
    SetPRCSwitch("PRC_FILE_END_cls_pres_fight", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_fistra", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_fom", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_foz", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_frebzk", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_gfkill", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_giant", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hath", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_havocm", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_heal", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_healer", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_heartw", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hexbl", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hextor", 24);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hiero", 12);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hmage", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hnshn", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hosp", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hotwm", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_hum", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_iaij", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_inidra", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_irnmnd", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_jpm", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_justww", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_kchal", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_knight", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_kord", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_kotmc", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_lasher", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_lgdr", 45);
    SetPRCSwitch("PRC_FILE_END_cls_pres_lich", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_maestr", 12);
    SetPRCSwitch("PRC_FILE_END_cls_pres_magbst", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_magek", 23);
    SetPRCSwitch("PRC_FILE_END_cls_pres_manat", 35);
    SetPRCSwitch("PRC_FILE_END_cls_pres_marsh", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_meph", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mharp", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mharpd", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_minstr", 22);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mon", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_monine", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_monk", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mos", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mstalc", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_myst", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_mystic", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_nights", 22);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ninja", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ninjca", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_noble", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ocular", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ollam", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ootbi", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ooze", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_orcus", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_orcwar", 15);
    SetPRCSwitch("PRC_FILE_END_cls_pres_out", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pal", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_palema", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_parch", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pdk", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_plant", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pnpasasin", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pnpblkgrd", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pnpsfr", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_psion", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_psych", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_psywar", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_pyro", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_rang", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_rava", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_rbyknt", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_redav", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_redwiz", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_rog", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_rune", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_runec", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sacfis", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_samur", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_savant", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sbheir", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_schord", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_scout", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sdmind", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shadep", 11);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shaman", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shape", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shdbld", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shou", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_shugen", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sklcln", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sleat", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sncmnd", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sod", 42);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sohei", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sol", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_sorc", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_soulkn", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_spellf", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_spells", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_ssn", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_storml", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_suel", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_swash", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_swdsge", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_swftwg", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_taltia", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tempst", 39);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tempus", 40);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tfshad", 9);
    SetPRCSwitch("PRC_FILE_END_cls_pres_thaykt", 7);
    SetPRCSwitch("PRC_FILE_END_cls_pres_thrall", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tnecro", 4);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tog", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tog_a", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_tog_d", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_true", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_undead", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_urang", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_vassal", 5);
    SetPRCSwitch("PRC_FILE_END_cls_pres_vermin", 1);
    SetPRCSwitch("PRC_FILE_END_cls_pres_vigil", 6);
    SetPRCSwitch("PRC_FILE_END_cls_pres_virt", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_warbld", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_warchf", 2);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wardark", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_warlok", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_warmnd", 3);
    SetPRCSwitch("PRC_FILE_END_cls_pres_warpr", 8);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wilder", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wiz", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wm", 38);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wrmage", 0);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wrslng", 20);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wwoc", 22);
    SetPRCSwitch("PRC_FILE_END_cls_pres_wwolf", 3);
    SetPRCSwitch("PRC_FILE_END_cls_psbk_foz", 39);
    SetPRCSwitch("PRC_FILE_END_cls_psbk_psion", 39);
    SetPRCSwitch("PRC_FILE_END_cls_psbk_psywar", 59);
    SetPRCSwitch("PRC_FILE_END_cls_psbk_warmnd", 39);
    SetPRCSwitch("PRC_FILE_END_cls_psbk_wilder", 59);
    SetPRCSwitch("PRC_FILE_END_cls_psipw_foz", 93);
    SetPRCSwitch("PRC_FILE_END_cls_psipw_psion", 262);
    SetPRCSwitch("PRC_FILE_END_cls_psipw_psywar", 98);
    SetPRCSwitch("PRC_FILE_END_cls_psipw_warmnd", 93);
    SetPRCSwitch("PRC_FILE_END_cls_psipw_wilder", 169);
    SetPRCSwitch("PRC_FILE_END_cls_savthr_lich", 59);
    SetPRCSwitch("PRC_FILE_END_cls_skill_adst", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_alag", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_alienist", 27);
    SetPRCSwitch("PRC_FILE_END_cls_skill_antipl", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_aots", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_arch", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_archer", 32);
    SetPRCSwitch("PRC_FILE_END_cls_skill_arclb", 32);
    SetPRCSwitch("PRC_FILE_END_cls_skill_arctrk", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_arti", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_asasin", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_baal", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_barb", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bard", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bereft", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bfz", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_blades", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_blarch", 33);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bldclw", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_blkgrd", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_blmagu", 33);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bltl", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bonded", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_bowman", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_brage", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_brawl", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_brimst", 34);
    SetPRCSwitch("PRC_FILE_END_cls_skill_cbtmed", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_cereb", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_chaban", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_cler", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_cntmp", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_coc", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_corup", 30);
    SetPRCSwitch("PRC_FILE_END_cls_skill_crea", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_crusdr", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dalqur", 37);
    SetPRCSwitch("PRC_FILE_END_cls_skill_deepst", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dfa", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_diabol", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_diadra", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dirge", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_disp", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_divcha", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dnecro", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_doa", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dradev", 34);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dradis", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drgnht", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drgshm", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drkwar", 33);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drnkn", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drowj", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_drslyr", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dru", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_duel", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_duskbl", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_dwdef", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_eldkni", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_enlfis", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_eog", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_etbl", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_favsol", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_fh", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_fight", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_fistra", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_fom", 31);
    SetPRCSwitch("PRC_FILE_END_cls_skill_foz", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_frebzk", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_gfkill", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hath", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_havocm", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_healer", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_heartw", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hexbl", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hextor", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hiero", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hmage", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hnshn", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hosp", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_hotwm", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_iaij", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_inidra", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_irnmnd", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_jpm", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_justww", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_kchal", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_kensei", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_knight", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_kord", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_kotmc", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_lasher", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_lgdr", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_maestr", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_magek", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_manat", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_marsh", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_meph", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_mharp", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_minstr", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_monine", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_monk", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_mos", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_mstalc", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_myst", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_mystic", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_nights", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ninja", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ninjca", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_noble", 37);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ocular", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ollam", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ootbi", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ooze", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_orcus", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_orcwar", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_pal", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_palema", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_parch", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_pdk", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_psion", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_psych", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_psywar", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_pyro", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_rang", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_rava", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_rbyknt", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_redav", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_redwiz", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_rog", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_rune", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_runec", 34);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sacfis", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_samur", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_savant", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sbheir", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_schord", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_scout", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sdmind", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shadep", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shadow", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shaman", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shdbld", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shiftr", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shou", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_shugen", 33);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sklcln", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sleat", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sncmnd", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sod", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sohei", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sol", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_sorc", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_soulkn", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_spellf", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_spells", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_ssn", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_storml", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_suel", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_swash", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_swdsge", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_swftwg", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_taltia", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_tempst", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_tempus", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_tfshad", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_thaykt", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_thrall", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_tnecro", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_tog", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_true", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_urang", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_vassal", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_vigil", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_virt", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_warbld", 36);
    SetPRCSwitch("PRC_FILE_END_cls_skill_warchf", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_warlok", 37);
    SetPRCSwitch("PRC_FILE_END_cls_skill_warmnd", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_warpr", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_waygde", 33);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wilder", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wiz", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wm", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wrmage", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wrslng", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wwoc", 35);
    SetPRCSwitch("PRC_FILE_END_cls_skill_wwolf", 35);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_antipl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_asasin", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_bard", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_blkgrd", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_dnecro", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_duskbl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_favsol", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_healer", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_hexbl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_justww", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_kchal", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_kotmc", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_myst", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_ocu", 29);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_shaman", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_sod", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_sohei", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_sol", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_sorc", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_suel", 29);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_tfshad", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_vassal", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_vigil", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spbk_wrmage", 59);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_antipl", 26);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_asasin", 46);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_bard", 152);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_blkgrd", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_dnecro", 66);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_duskbl", 62);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_favsol", 256);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_healer", 54);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_hexbl", 45);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_justww", 25);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_kchal", 34);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_kotmc", 19);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_myst", 256);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_ocu", 165);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_shaman", 91);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_sod", 22);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_sohei", 41);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_sol", 30);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_sorc", 395);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_suel", 108);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_tfshad", 27);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_vassal", 22);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_vigil", 17);
    SetPRCSwitch("PRC_FILE_END_cls_spcr_wrmage", 80);
    SetPRCSwitch("PRC_FILE_END_cls_spell_antipl", 89);
    SetPRCSwitch("PRC_FILE_END_cls_spell_asasin", 108);
    SetPRCSwitch("PRC_FILE_END_cls_spell_bard", 684);
    SetPRCSwitch("PRC_FILE_END_cls_spell_blkgrd", 152);
    SetPRCSwitch("PRC_FILE_END_cls_spell_dnecro", 300);
    SetPRCSwitch("PRC_FILE_END_cls_spell_duskbl", 327);
    SetPRCSwitch("PRC_FILE_END_cls_spell_favsol", 1326);
    SetPRCSwitch("PRC_FILE_END_cls_spell_healer", 234);
    SetPRCSwitch("PRC_FILE_END_cls_spell_hexbl", 164);
    SetPRCSwitch("PRC_FILE_END_cls_spell_justww", 61);
    SetPRCSwitch("PRC_FILE_END_cls_spell_kchal", 117);
    SetPRCSwitch("PRC_FILE_END_cls_spell_kotmc", 55);
    SetPRCSwitch("PRC_FILE_END_cls_spell_myst", 1326);
    SetPRCSwitch("PRC_FILE_END_cls_spell_ocu", 695);
    SetPRCSwitch("PRC_FILE_END_cls_spell_shaman", 477);
    SetPRCSwitch("PRC_FILE_END_cls_spell_SOD", 58);
    SetPRCSwitch("PRC_FILE_END_cls_spell_sohei", 123);
    SetPRCSwitch("PRC_FILE_END_cls_spell_sol", 94);
    SetPRCSwitch("PRC_FILE_END_cls_spell_sorc", 2244);
    SetPRCSwitch("PRC_FILE_END_cls_spell_suel", 514);
    SetPRCSwitch("PRC_FILE_END_cls_spell_tfshad", 62);
    SetPRCSwitch("PRC_FILE_END_cls_spell_vassal", 72);
    SetPRCSwitch("PRC_FILE_END_cls_spell_vigil", 52);
    SetPRCSwitch("PRC_FILE_END_cls_spell_wrmage", 423);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_asasin", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_dnecro", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_duskbl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_favsol", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_hexbl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_justww", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_myst", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_suel", 39);
    SetPRCSwitch("PRC_FILE_END_cls_spkn_wrmage", 39);
    SetPRCSwitch("PRC_FILE_END_cls_true_known", 39);
    SetPRCSwitch("PRC_FILE_END_cls_true_maxlvl", 39);
    SetPRCSwitch("PRC_FILE_END_cls_true_utter", 166);
    SetPRCSwitch("PRC_FILE_END_colours", 175);
    SetPRCSwitch("PRC_FILE_END_des_crft_scroll", 3848);
    SetPRCSwitch("PRC_FILE_END_des_crft_spells", 19335);
    SetPRCSwitch("PRC_FILE_END_des_matcomp", 510);
    SetPRCSwitch("PRC_FILE_END_disease", 62);
    SetPRCSwitch("PRC_FILE_END_dmgxp", 59);
    SetPRCSwitch("PRC_FILE_END_domains", 59);
    SetPRCSwitch("PRC_FILE_END_ECL", 254);
    SetPRCSwitch("PRC_FILE_END_epicspells", 70);
    SetPRCSwitch("PRC_FILE_END_epicspellseeds", 27);
    SetPRCSwitch("PRC_FILE_END_feat", 24400);
    SetPRCSwitch("PRC_FILE_END_fileends", 20);
    SetPRCSwitch("PRC_FILE_END_hen_familiar", 11);
    SetPRCSwitch("PRC_FILE_END_iprp_aoe", 5);
    SetPRCSwitch("PRC_FILE_END_iprp_casterlvl", 60);
    SetPRCSwitch("PRC_FILE_END_iprp_costtable", 39);
    SetPRCSwitch("PRC_FILE_END_iprp_damagecost", 70);
    SetPRCSwitch("PRC_FILE_END_iprp_decvalue1", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_decvalue2", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_feats", 24704);
    SetPRCSwitch("PRC_FILE_END_iprp_incvalue1", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_incvalue2", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_maxpp", 8);
    SetPRCSwitch("PRC_FILE_END_iprp_metamagic", 6);
    SetPRCSwitch("PRC_FILE_END_iprp_monstcost", 58);
    SetPRCSwitch("PRC_FILE_END_iprp_neg5cost", 10);
    SetPRCSwitch("PRC_FILE_END_iprp_onhitcost", 70);
    SetPRCSwitch("PRC_FILE_END_iprp_onhitdur", 27);
    SetPRCSwitch("PRC_FILE_END_iprp_onhitspell", 209);
    SetPRCSwitch("PRC_FILE_END_iprp_resistcost", 28);
    SetPRCSwitch("PRC_FILE_END_iprp_soakcost", 50);
    SetPRCSwitch("PRC_FILE_END_iprp_speed_dec", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_speed_enh", 9);
    SetPRCSwitch("PRC_FILE_END_iprp_spellcost", 243);
    SetPRCSwitch("PRC_FILE_END_iprp_spells", 1416);
    SetPRCSwitch("PRC_FILE_END_iprp_srcost", 61);
    SetPRCSwitch("PRC_FILE_END_iprp_storedpp", 16);
    SetPRCSwitch("PRC_FILE_END_iprp_weightcost", 6);
    SetPRCSwitch("PRC_FILE_END_itempropdef", 199);
    SetPRCSwitch("PRC_FILE_END_itemprops", 199);
    SetPRCSwitch("PRC_FILE_END_masterfeats", 113);
    SetPRCSwitch("PRC_FILE_END_material", 3223);
    SetPRCSwitch("PRC_FILE_END_phenotype", 33);
    SetPRCSwitch("PRC_FILE_END_poison", 146);
    SetPRCSwitch("PRC_FILE_END_poisontypedef", 3);
    SetPRCSwitch("PRC_FILE_END_polymorph", 155);
    SetPRCSwitch("PRC_FILE_END_prc_rune_craft", 7);
    SetPRCSwitch("PRC_FILE_END_shifterlist", 30);
    SetPRCSwitch("PRC_FILE_END_shifter_abilitie", 116);
    SetPRCSwitch("PRC_FILE_END_shifter_feats", 424);
    SetPRCSwitch("PRC_FILE_END_skills", 38);
    SetPRCSwitch("PRC_FILE_END_spells", 19335);
    SetPRCSwitch("PRC_FILE_END_spellschools", 9);
    SetPRCSwitch("PRC_FILE_END_templates", 105);
    SetPRCSwitch("PRC_FILE_END_traps", 101);
    SetPRCSwitch("PRC_FILE_END_unarmed_dmg", 13);
    SetPRCSwitch("PRC_FILE_END_vfx_persistent", 254);
    SetPRCSwitch("PRC_FILE_END_visualeffects", 1326);
    //END AUTO-GENERATED FILEENDS


    //Overriding fileends
    SetPRCSwitch("PRC_FILE_END_feat", 390);
    SetPRCSwitch("PRC_FILE_END_spells", 539);
    //SetPRCSwitch("PRC_FILE_END_iprp_feats", 17993);
    SetPRCSwitch("PRC_FILE_END_iprp_feats", 40);
    //SetPRCSwitch("PRC_FILE_END_iprp_spells", 1379);
    

    //there is also the fileends.2da file, but that
    //isnt read in here yet. may be later though
    if(GetPRCSwitch(FILE_END_MANUAL))
        return;
    SetPRCSwitch(FILE_END_CLASSES,         PRCGetFileEnd("classes"));
    SetPRCSwitch(FILE_END_RACIALTYPES,     PRCGetFileEnd("racialtypes"));
    SetPRCSwitch(FILE_END_GENDER,          1);//overriden to 1 for convoCC m/f only choice
    SetPRCSwitch(FILE_END_PORTRAITS,       PRCGetFileEnd("portraits"));
    SetPRCSwitch(FILE_END_SKILLS,          PRCGetFileEnd("skills"));
    SetPRCSwitch(FILE_END_CLASS_FEAT,      600);
    SetPRCSwitch(FILE_END_CLASS_SKILLS,    50);
    SetPRCSwitch(FILE_END_CLASS_POWER,     300);
    SetPRCSwitch(FILE_END_CLASS_SPELLBOOK, PRCGetFileEnd("cls_spell_sorc")); //sorc is 1957
    SetPRCSwitch(FILE_END_FEAT,            PRCGetFileEnd("feat"));
    SetPRCSwitch(FILE_END_CLASS_PREREQ,    25);
    SetPRCSwitch(FILE_END_FAMILIAR,        PRCGetFileEnd("hen_familiar"));
    SetPRCSwitch(FILE_END_ANIMALCOMP,      PRCGetFileEnd("hen_companion"));
    SetPRCSwitch(FILE_END_DOMAINS,         PRCGetFileEnd("domains"));
    SetPRCSwitch(FILE_END_SOUNDSET,        PRCGetFileEnd("soundset"));
    SetPRCSwitch(FILE_END_SPELLS,          PRCGetFileEnd("spells"));
    SetPRCSwitch(FILE_END_SPELLSCHOOL,     PRCGetFileEnd("spellschools"));
    SetPRCSwitch(FILE_END_APPEARANCE,      PRCGetFileEnd("appearance"));
    SetPRCSwitch(FILE_END_WINGS,           PRCGetFileEnd("wingmodel"));
    SetPRCSwitch(FILE_END_TAILS,           PRCGetFileEnd("tailmodel"));
    SetPRCSwitch(FILE_END_PACKAGE,         PRCGetFileEnd("packages"));
    SetPRCSwitch(FILE_END_RACE_FEAT,       30);
    SetPRCSwitch(FILE_END_BASEITEMS,       PRCGetFileEnd("baseitems"));
}

void CreateSwitchNameArray()
{
    object oWP = GetWaypointByTag("PRC_Switch_Name_WP");
    if(!GetIsObjectValid(oWP))
        oWP = CreateObject(OBJECT_TYPE_WAYPOINT, "NW_WAYPOINT001", GetStartingLocation(), FALSE, "PRC_Switch_Name_WP");
    if(!GetIsObjectValid(oWP))
        PrintString("CreateSwitchNameArray: Problem creating waypoint.");
    array_create(oWP, "Switch_Name");
    //if you add more switches, add them to this list
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_TRUESEEING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_TRUESEEING_SPOT_BONUS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_GRRESTORE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_HEAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_MASS_HEAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_HARM);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_NEUTRALIZE_POISON);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_REMOVE_DISEASE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TIMESTOP_BIOWARE_DURATION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TIMESTOP_LOCAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TIMESTOP_NO_HOSTILE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TIMESTOP_BLANK_PC);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_ELEMENTAL_SWARM);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_FEAR_AURAS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_TENSERS_TRANSFORMATION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_BLACK_BLADE_OF_DISASTER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_FIND_TRAPS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_DARKNESS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_DARKNESS_35ED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_ANIMATE_DEAD);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CREATE_UNDEAD_PERMANENT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CREATE_UNDEAD_UNCONTROLLED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_NEC_TERM_PERMADEATH);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELL_ALIGNMENT_SHIFT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_35ED_WORD_OF_FAITH);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SLEEP_NO_HD_CAP);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_165_DEATH_IMMUNITY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_NEW_IMBUE_ARROW);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DRAGON_DISCIPLE_SIZE_CHANGES);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SAMURAI_ALLOW_STOLEN_SACRIFICE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SAMURAI_ALLOW_UNIDENTIFIED_SACRIFICE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SAMURAI_SACRIFICE_SCALAR_x100);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SAMURAI_VALUE_SCALAR_x100);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ORC_WARLORD_COHORT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_LICH_ALTER_SELF_DISABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TRUE_NECROMANCER_ALTERNATE_VISUAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_THRALLHERD_LEADERSHIP);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_XP_COSTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_TAKE_TEN_RULE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_PRIMARY_ABILITY_MODIFIER_RULE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_BACKLASH_DAMAGE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_FOCI_ADJUST_DC);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_GOLD_MULTIPLIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_XP_FRACTION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_FAILURE_FRACTION_GOLD);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_BOOK_DESTRUCTION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_UNIMPINGED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_IMPENETRABILITY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_DULLBLADES);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_CHAMPIONS_VALOR);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_EPIC_CONVO_LEARNING_DISABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_STAFF_CASTER_LEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_NPC_HAS_PC_SPELLCASTING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ECL_USES_XP_NOT_HD);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_DEMILICH);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELLSLAB);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELLSLAB_NOSCROLLS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_ABILITY_DAMAGE_EFFECTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SUPPLY_BASED_REST);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_REST_HEALING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_REST_TIME);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_SPELL_SCHOOLS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PLAYER_TIME);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_SOMATIC_COMPOMENTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_SOMATIC_ITEMS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_MULTISUMMON);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SUMMON_ROUND_PER_LEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_FAMILIARS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_FAMILIAR_FEEDING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_NO_FREE_WIZ_SPELLS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_POWER_ATTACK);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_POWER_ATTACK_STACK_WITH_BW);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_NO_PETRIFY_GUI);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_SWITCH_CHANGING_CONVO);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_DOMAIN_ENFORCEMENT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BONUS_COHORTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_CUSTOM_COHORTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_STANDARD_COHORTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_REGISTER_COHORTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_SLINGS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BEBILITH_CLAWS_DESTROY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_AUTO_IDENTIFY_ON_ACQUIRE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_AUTO_UNIDENTIFY_ON_UNACQUIRE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELLFIRE_DISALLOW_CHARGE_SELF);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELLFIRE_DISALLOW_DRAIN_SCROLL_POTION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SORC_DISALLOW_NEWSPELLBOOK);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BARD_DISALLOW_NEWSPELLBOOK);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CWSAMURAI_NO_HEIRLOOM_DAISHO);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_CONVO_TEMPLATE_GAIN);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_ARMOR_SPEED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_RACIAL_SPEED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_REMOVE_PLAYER_SPEED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ENFORCE_RACIAL_APPEARANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_NPC_FORCE_RACE_ACQUIRE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DYNAMIC_CLOAK_AUTOCOLOUR_DISABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_STABLE_TO_DISABLED_CHANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_STABLE_TO_BLEED_CHANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_BLEED_TO_STABLE_CHANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_HEAL_FROM_STABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_DAMAGE_FROM_STABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_DAMAGE_FROM_BLEEDING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_TIME_BETWEEN_DEATH);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_TIME_BETWEEN_DISABLED);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_TIME_BETWEEN_STABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEATH_TIME_BETWEEN_BLEEDING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_DEATH_ENABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ACP_MANUAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ACP_AUTOMATIC);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ACP_NPC_AUTOMATIC);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ACP_DELAY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_TAGBASED_INDEX_FOR_POISON);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USES_PER_ITEM_POISON_COUNT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USES_PER_ITEM_POISON_DIE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ALLOW_ONLY_SHARP_WEAPONS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ALLOW_ALL_POISONS_ON_WEAPONS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_DEXBASED_WEAPON_POISONING_FAILURE_CHANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USES_PER_WEAPON_POISON_COUNT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USES_PER_WEAPON_POISON_DIE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_POISON_ALLOW_CLEAN_IN_EQUIP);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PSI_ASTRAL_CONSTRUCT_USE_2DA);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_RAPID_METABOLISM);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PSI_IMP_METAPSIONICS_USE_SUM);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_USECR);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_S_HUGE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_S_LARGE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_S_MEDIUM);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_S_SMALL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_S_TINY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_OUTSIDER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_ELEMENTAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_CONSTRUCT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_UNDEAD);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_DRAGON);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_ABERRATION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_OOZE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_MAGICALBEAST);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_GIANT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_VERMIN);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_BEAST);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_ANIMAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_MONSTROUSHUMANOID);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PNP_SHFT_F_HUMANOID);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PNP_ELEMENTAL_DAMAGE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELL_SNEAK_DISABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_3_5e_FIST_DAMAGE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BRAWLER_SIZE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_APPEARANCE_SIZE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_MONK_ATTACKS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SMALL_CREATURE_FINESSE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BIOWARE_DIVINE_POWER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_ALLOW_SWITCH_OF_TARGET);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_COUP_DE_GRACE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_FLAME_WEAPON_DAMAGE_MAX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DARKFIRE_DAMAGE_MAX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_CRAFT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFT_TIMER_MULTIPLIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFT_TIMER_MAX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFT_TIMER_MIN);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_BREW_POTION_CASTER_LEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SCRIBE_SCROLL_CASTER_LEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFT_WAND_CASTER_LEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFTING_BASE_ITEMS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), X2_CI_BREWPOTION_MAXLEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), X2_CI_BREWPOTION_COSTMODIFIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), X2_CI_SCRIBESCROLL_COSTMODIFIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), X2_CI_CRAFTWAND_MAXLEVEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), X2_CI_CRAFTWAND_COSTMODIFIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFTING_ARBITRARY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFTING_COST_SCALE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CRAFTING_TIME_SCALE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TELEPORT_MAX_TARGET_LOCATIONS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DISABLE_TELEPORTATION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_TIME);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_PC_AUTOEXPORT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_HP_TRACKING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_LOCATION_TRACKING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_MAPPIN_TRACKING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_DEATH_TRACKING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PW_SPELL_TRACKING);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_XP_USE_SIMPLE_LA);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_XP_USE_SIMPLE_RACIAL_HD);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_XP_USE_SIMPLE_RACIAL_HD_NO_FREE_XP);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_XP_USE_SIMPLE_RACIAL_HD_NO_SELECTION);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_XP_USE_SETXP);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_DATABASE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_BIOWARE_DATABASE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DB_PRECACHE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DB_SQLITE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DB_SQLITE_INTERVAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DB_MYSQL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_USE_LETOSCRIPT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_LETOSCRIPT_PHEONIX_SYNTAX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_LETOSCRIPT_FIX_ABILITIES);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_LETOSCRIPT_UNICORN_SQL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_LETOSCRIPT_GETNEWESTBIC);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ENABLE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_AVARIEL_WINGS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_FEYRI_WINGS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_AASIMAR_WINGS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_FEYRI_TAIL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_TIEFLING_TAIL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_DROW_ENFORCE_GENDER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_GENASI_ENFORCE_DOMAINS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_RAKSHASA_FEMALE_APPEARANCE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ENFORCE_PNP_RACIAL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ENFORCE_FEATS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_DISALLOW_CUSTOMISE_WINGS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_DISALLOW_CUSTOMISE_TAIL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_DISALLOW_CUSTOMISE_MODEL);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_USE_RACIAL_APPEARANCES);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_USE_RACIAL_PORTRAIT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ONLY_PLAYER_VOICESETS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_RESTRICT_VOICESETS_BY_SEX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ALLOW_TO_KEEP_VOICESET);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ALLOW_TO_KEEP_PORTRAIT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_RESTRICT_PORTRAIT_BY_SEX);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ENABLE_RACIAL_HITDICE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ALLOW_SKILL_POINT_ROLLOVER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_USE_XP_FOR_NEW_CHAR);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_ENCRYPTION_KEY);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_STAT_POINTS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_BONUS_FEATS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_MAX_STAT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_SKILL_MULTIPLIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_SKILL_BONUS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_CONVOCC_CUSTOM_EXIT_SCRIPT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TRUENAME_CR_MULTIPLIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TRUENAME_LEVEL_BONUS);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_TRUENAME_DC_CONSTANT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PERFECTED_MAP_CONSTANT);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_PERFECTED_MAP_MULTIPLIER);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_DEBUG);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_COMBAT_DEBUG);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_SPELLCASTITEM_OVERRIDE);
    array_set_string(oWP, "Switch_Name", array_get_size(oWP, "Switch_Name"), PRC_AFTS_EXTRA_DAMAGE);
}
