
//const int FEAT_WEAPON_FOCUS_WHIP      = 993;
//const int FEAT_IMPROVED_CRITICAL_WHIP = 995;

//iprp_feats

const int IP_CONST_FEAT_SNEAKATK1     = 32;
const int IP_CONST_FEAT_SNEAKATK2     = 33;
const int IP_CONST_FEAT_SNEAKATK3     = 34;
const int IP_CONST_FEAT_SNEAKATK4     = 301;
const int IP_CONST_FEAT_SNEAKATK5     = 39;
const int IP_CONST_FEAT_SNEAKATK6     = 302;
const int IP_CONST_FEAT_SNEAKATK7     = 303;
const int IP_CONST_FEAT_SNEAKATK8     = 304;
const int IP_CONST_FEAT_SNEAKATK9     = 305;
const int IP_CONST_FEAT_SNEAKATK10    = 306;
const int IP_CONST_FEAT_SNEAKATK11    = 307;
const int IP_CONST_FEAT_SNEAKATK12    = 308;
const int IP_CONST_FEAT_SNEAKATK13    = 309;
const int IP_CONST_FEAT_SNEAKATK14    = 310;
const int IP_CONST_FEAT_SNEAKATK15    = 311;
const int IP_CONST_FEAT_SNEAKATK16    = 312;
const int IP_CONST_FEAT_SNEAKATK17    = 313;
const int IP_CONST_FEAT_SNEAKATK18    = 314;
const int IP_CONST_FEAT_SNEAKATK19    = 315;
const int IP_CONST_FEAT_SNEAKATK20    = 316;
const int IP_CONST_FEAT_DEATHATTACK   = 317;
const int IP_CONST_FEAT_DEATHATTACK2   = 318;
const int IP_CONST_FEAT_DEATHATTACK3   = 319;
const int IP_CONST_FEAT_DEATHATTACK4   = 320;
const int IP_CONST_FEAT_DEATHATTACK5   = 321;
const int IP_CONST_FEAT_DEATHATTACK6   = 322;
const int IP_CONST_FEAT_DEATHATTACK7   = 323;
const int IP_CONST_FEAT_DEATHATTACK8   = 324;
const int IP_CONST_FEAT_DEATHATTACK9   = 325;
const int IP_CONST_FEAT_DEATHATTACK10  = 326;
const int IP_CONST_FEAT_DEATHATTACK11  = 327;
const int IP_CONST_FEAT_DEATHATTACK12  = 328;
const int IP_CONST_FEAT_DEATHATTACK13  = 329;
const int IP_CONST_FEAT_DEATHATTACK14  = 330;
const int IP_CONST_FEAT_DEATHATTACK15  = 331;
const int IP_CONST_FEAT_DEATHATTACK16  = 332;
const int IP_CONST_FEAT_DEATHATTACK17  = 333;
const int IP_CONST_FEAT_DEATHATTACK18  = 334;
const int IP_CONST_FEAT_DEATHATTACK19  = 335;
const int IP_CONST_FEAT_DEATHATTACK20  = 336;
const int IP_CONST_FEAT_BarbEndurance  = 337;
const int IP_CONST_FEAT_WeapFocCreature      = 338;
const int IP_CONST_FEAT_ImpCritCreature      = 339;
const int IP_CONST_FEAT_WeapSpecCreature     = 340;
const int IP_CONST_FEAT_WeapEpicFocCreature  = 341;
const int IP_CONST_FEAT_WeapEpicSpecCreature = 342;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DAGGER  = 343;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DART  = 344;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HEAVY_CROSSBOW  = 345;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_CROSSBOW  = 346;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_MACE  = 347;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_MORNING_STAR  = 348;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_STAFF  = 349;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SPEAR  = 350;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SICKLE  = 351;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SLING  = 352;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LONGBOW  = 353;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHORTBOW  = 354;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHORT_SWORD = 355;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_RAPIER  = 356;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SCIMITAR  = 357;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LONG_SWORD  = 358;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_GREAT_SWORD  = 359;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HAND_AXE  = 360;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_THROWING_AXE  = 361;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_BATTLE_AXE  = 362;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_GREAT_AXE  = 363;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HALBERD  = 364;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_HAMMER  = 365;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_FLAIL  = 366;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_WAR_HAMMER  = 367;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HEAVY_FLAIL  = 368;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KAMA  = 369;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KUKRI  = 370;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHURIKEN  = 371;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SCYTHE  = 372;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KATANA  = 373;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_BASTARD_SWORD  = 374;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DIRE_MACE  = 375;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DOUBLE_AXE  = 376;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_TWO_BLADED_SWORD  = 377;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_CLUB  = 378;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DWAXE  = 379;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_WHIP = 380;
const int IP_CONST_FEAT_SF_CODE = 381;
const int IP_CONST_FEAT_UNCANNY_DODGE1 = 382;
const int IP_CONST_FEAT_LOWLIGHT_VISION = 383;
const int IP_CONST_FEAT_NEW_PWATK = 384;
const int IP_CONST_FEAT_NEW_IPWATK = 385;
const int IP_CONST_FEAT_KI_STRIKE = 254;

const int IP_CONST_FEAT_REND         = 255;
const int IP_CONST_FEAT_SPELL10      = 256;
const int IP_CONST_FEAT_MOBILITY     = 27;
const int IP_CONST_FEAT_WHIRLWIND    = 29;
const int IP_CONST_FEAT_BLINDFIGHT   = 257;
const int IP_CONST_FEAT_SPRINGATTACK = 258;


// IP_CONST_CASTSPELL

const int IP_CONST_CASTSPELL_BLESSWEAPON_10 = 13;
const int IP_CONST_CASTSPELL_MAGICWEAPON_2 = 479;
const int IP_CONST_CASTSPELL_GREATERMAGICWEAPON_10 = 511;
const int IP_CONST_CASTSPELL_GREATERMAGICWEAPON_11 = 512;
const int IP_CONST_CASTSPELL_HOLY_SWORD_15 = 473;

const int IP_CONST_CASTSPELL_GRENADE_POISONVIAL = 1140;
const int IP_CONST_CASTSPELL_POISON_WEAPON      = 1141;
const int IP_CONST_CASTSPELL_POISON_ITEM        = 1142;
const int IP_CONST_CASTSPELL_POISON_FOOD        = 1143;
const int IP_CONST_CASTSPELL_CLEAN_POISON_OFF   = 1144;


//  IP_CONST_ONHIT_CASTSPELL

const int IP_CONST_ONHIT_CASTSPELL_RAVAGEGOLDENICE = 200;
const int IP_CONST_ONHIT_CASTSPELL_NIGHTSHADEPOISON = 201;
const int IP_CONST_ONHIT_CASTSPELL_LINGDMG = 202;

//  IP_CONST_DAMAGEBONUS

const int IP_CONST_DAMAGEBONUS_11 = 21;
const int IP_CONST_DAMAGEBONUS_12 = 22;
const int IP_CONST_DAMAGEBONUS_13 = 23;
const int IP_CONST_DAMAGEBONUS_14 = 24;
const int IP_CONST_DAMAGEBONUS_15 = 25;
const int IP_CONST_DAMAGEBONUS_16 = 26;
const int IP_CONST_DAMAGEBONUS_17 = 27;
const int IP_CONST_DAMAGEBONUS_18 = 28;
const int IP_CONST_DAMAGEBONUS_19 = 29;
const int IP_CONST_DAMAGEBONUS_20 = 30;
const int IP_CONST_DAMAGEBONUS_3D6 = 71;
const int IP_CONST_DAMAGEBONUS_4D6 = 72;
const int IP_CONST_DAMAGEBONUS_5D6 = 73;
const int IP_CONST_DAMAGEBONUS_6D6 = 74;
const int IP_CONST_DAMAGEBONUS_7D6 = 75;
const int IP_CONST_DAMAGEBONUS_8D6 = 76;
const int IP_CONST_DAMAGEBONUS_3D4 = 77;
const int IP_CONST_DAMAGEBONUS_4D4 = 78;
const int IP_CONST_DAMAGEBONUS_5D4 = 79;
const int IP_CONST_DAMAGEBONUS_6D4 = 80;

// IP_CONST_IMMUNITYSPELL

const int IP_CONST_IMMUNITYSPELL_BOLT_WEB     =  239;
const int IP_CONST_IMMUNITYSPELL_SHADOW_WEB   =  240;
const int IP_CONST_IMMUNITYSPELL_BELETITH_WEB =  241;
const int IP_CONST_IMMUNITYSPELL_NS_WEB       =  242;

// IP_CONST_ONHIT_SAVEDC

const int IP_CONST_ONHIT_SAVEDC_17 = 17;
const int IP_CONST_ONHIT_SAVEDC_19 = 19;

// Creature Epic Criticals
const int IP_CONST_FEAT_DEVCRITICAL_CREATURE	= 271;
const int IP_CONST_FEAT_OVERCRITICAL_CREATURE	= 272;
const int IP_CONST_FEAT_WEAPON_PROF_CREATURE	= 38;

// Epic DR
const int IP_CONST_FEAT_EPIC_DR_3             = 273;
const int IP_CONST_FEAT_EPIC_DR_6             = 274;
const int IP_CONST_FEAT_EPIC_DR_9             = 275;

//IP_CONST_DAMAGETYPE
const int IP_CONST_DAMAGETYPE_VILE            = 14;

//IP_CONST_DAMAGESOAK
const int IP_CONST_DAMAGESOAK_1_HP = 11;
const int IP_CONST_DAMAGESOAK_2_HP = 12;
const int IP_CONST_DAMAGESOAK_3_HP = 13;
const int IP_CONST_DAMAGESOAK_4_HP = 14;
const int IP_CONST_DAMAGESOAK_6_HP = 15;
const int IP_CONST_DAMAGESOAK_7_HP = 16;
const int IP_CONST_DAMAGESOAK_8_HP = 17;
const int IP_CONST_DAMAGESOAK_9_HP = 18;
const int IP_CONST_DAMAGESOAK_11_HP = 19;
const int IP_CONST_DAMAGESOAK_12_HP = 20;
const int IP_CONST_DAMAGESOAK_13_HP = 21;
const int IP_CONST_DAMAGESOAK_14_HP = 22;
const int IP_CONST_DAMAGESOAK_16_HP = 23;
const int IP_CONST_DAMAGESOAK_17_HP = 24;
const int IP_CONST_DAMAGESOAK_18_HP = 25;
const int IP_CONST_DAMAGESOAK_19_HP = 26;
const int IP_CONST_DAMAGESOAK_21_HP = 27;
const int IP_CONST_DAMAGESOAK_22_HP = 28;
const int IP_CONST_DAMAGESOAK_23_HP = 29;
const int IP_CONST_DAMAGESOAK_24_HP = 30;
const int IP_CONST_DAMAGESOAK_26_HP = 31;
const int IP_CONST_DAMAGESOAK_27_HP = 32;
const int IP_CONST_DAMAGESOAK_28_HP = 33;
const int IP_CONST_DAMAGESOAK_29_HP = 34;
const int IP_CONST_DAMAGESOAK_31_HP = 35;
const int IP_CONST_DAMAGESOAK_32_HP = 36;
const int IP_CONST_DAMAGESOAK_33_HP = 37;
const int IP_CONST_DAMAGESOAK_34_HP = 38;
const int IP_CONST_DAMAGESOAK_36_HP = 39;
const int IP_CONST_DAMAGESOAK_37_HP = 40;
const int IP_CONST_DAMAGESOAK_38_HP = 41;
const int IP_CONST_DAMAGESOAK_39_HP = 42;
const int IP_CONST_DAMAGESOAK_41_HP = 43;
const int IP_CONST_DAMAGESOAK_42_HP = 44;
const int IP_CONST_DAMAGESOAK_43_HP = 45;
const int IP_CONST_DAMAGESOAK_44_HP = 46;
const int IP_CONST_DAMAGESOAK_46_HP = 47;
const int IP_CONST_DAMAGESOAK_47_HP = 48;
const int IP_CONST_DAMAGESOAK_48_HP = 49;
const int IP_CONST_DAMAGESOAK_49_HP = 50;

//IP_CONST_DAMAGERESIST
const int IP_CONST_DAMAGERESIST_500 = 20; // immunity alternative
const int IP_CONST_DAMAGERESIST_1 = 21; 
const int IP_CONST_DAMAGERESIST_2 = 22; 
const int IP_CONST_DAMAGERESIST_3 = 23; 
const int IP_CONST_DAMAGERESIST_4 = 24; 

// IP_CONST_MONSTERDAMAGE
const int IP_CONST_MONSTERDAMAGE_7d4 = 58;