
const int IP_CONST_SPELLRESISTANCEBONUS_34 = 34;
const int IP_CONST_SPELLRESISTANCEBONUS_36 = 36;
const int IP_CONST_SPELLRESISTANCEBONUS_38 = 38;
const int IP_CONST_SPELLRESISTANCEBONUS_40 = 40;
const int IP_CONST_SPELLRESISTANCEBONUS_42 = 42;
const int IP_CONST_SPELLRESISTANCEBONUS_44 = 44;
const int IP_CONST_SPELLRESISTANCEBONUS_46 = 46;
const int IP_CONST_SPELLRESISTANCEBONUS_48 = 48;
const int IP_CONST_SPELLRESISTANCEBONUS_50 = 50;
const int IP_CONST_SPELLRESISTANCEBONUS_52 = 52;
const int IP_CONST_SPELLRESISTANCEBONUS_54 = 54;
const int IP_CONST_SPELLRESISTANCEBONUS_56 = 56;
const int IP_CONST_SPELLRESISTANCEBONUS_58 = 58;
const int IP_CONST_SPELLRESISTANCEBONUS_60 = 60;

