/*
 * CreditsMenu.java
 *
 * Created on April 4, 2003, 5:33 PM
 */

package CharacterCreator;

import java.awt.*;
/**
 *
 * @author  James
 */
public class CreditsMenu extends javax.swing.JFrame {
    
    /** Creates new form CreditsMenu */
    public CreditsMenu() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        if ( (screenSize.getWidth() > getContentPane().getWidth()) && (screenSize.getHeight() > getContentPane().getHeight())) {
            int intwidth = new Double(((screenSize.getWidth()-getContentPane().getWidth())/2)).intValue();
            int intheight = new Double(((screenSize.getHeight()-getContentPane().getHeight())/2)).intValue();            
            setLocation(intwidth, intheight);
        } else {
            setLocation(0,0);
        }        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        CreditText = new javax.swing.JTextArea();
        OKButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 303));
        CreditText.setBackground(new java.awt.Color(51, 51, 51));
        CreditText.setEditable(false);
        CreditText.setForeground(new java.awt.Color(204, 204, 0));
        CreditText.setLineWrap(true);
        CreditText.setWrapStyleWord(true);
        CreditText.setText("PRC: v1.3\nThis release was prepared by the "
				+ "Player Resource Consortium so we could make Level 40 Drow "
				+ "Samurai.\n\nv1.1\nThis version was a team effort.  Thanks "
				+ "go to James, grond and Garad Moonbeam for getting the "
				+ "updates done for SoU and 1.3x compatability as well as "
				+ "dynamic skill menus.\nThanks go to Papermonk, first of all, "
				+ "for possessing the\nintestinal fortitude to stick with me "
				+ "on this project. Many\npeople said it couldn't be done, but "
				+ "here it is!\n\nThanks also go to the whole CODI gang, "
				+ "specifically\nShkuey, Snowmit, Smeazel, Jupp, batinthehat, "
				+ "MacIntyre,\nand Permagrin; also to the few external alpha "
				+ "testers I\nhad, and everyone else who supported this "
				+ "project. \nSpecific thanks go to GL (rabbithail) for "
				+ "helping me hash\nout ELC issues with the program, and "
				+ "sticking with me. \nThanks also go to Torlack for having "
				+ "such an incredible\ninformation source; Maximus at the "
				+ "NWVault for supporting\nCODI so much; RedR for hosting our "
				+ "chat room, and of\ncourse, Bioware for making such a great "
				+ "game.\n\nHappy custom character creating!");
        CreditText.setMargin(new java.awt.Insets(10, 10, 10, 10));
        CreditText.setMinimumSize(new java.awt.Dimension(360, 244));
        CreditText.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(CreditText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(OKButton, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel5, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();             
    }//GEN-LAST:event_OKButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
        dispose();     
    }//GEN-LAST:event_exitForm
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton OKButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea CreditText;
    // End of variables declaration//GEN-END:variables
    
}
