/*
 * SexMenu1.java
 *
 * Created on April 4, 2003, 3:17 PM
 */

package CharacterCreator;

import java.awt.*;
import java.awt.event.*;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
/**
 *
 * @author  James
 */
public class SexMenu extends javax.swing.JFrame {
    
    /** Creates new form SexMenu1 */
    public SexMenu() {
        menucreate = TLKFactory.getCreateMenu();        
        menucreate.BlockWindow(true);        
        initComponents();
        OKButton.setEnabled(false);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        if ( (screenSize.getWidth() > getContentPane().getWidth()) && (screenSize.getHeight() > getContentPane().getHeight())) {
            int intwidth = new Double(((screenSize.getWidth()-getContentPane().getWidth())/2)).intValue();
            int intheight = new Double(((screenSize.getHeight()-getContentPane().getHeight())/2)).intValue();            
            setLocation(intwidth, intheight);
        } else {
            setLocation(0,0);
        }           
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        GenderButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        MaleButton = new javax.swing.JToggleButton();
        FemaleButton = new javax.swing.JToggleButton();
        BothButton = new javax.swing.JToggleButton();
        OtherButton = new javax.swing.JToggleButton();
        NoneButton = new javax.swing.JToggleButton();
        CancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Gender");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jPanel4, gridBagConstraints);

        MaleButton.setText("Male");
        GenderButtons.add(MaleButton);
        MaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(MaleButton, gridBagConstraints);

        FemaleButton.setText("Female");
        GenderButtons.add(FemaleButton);
        FemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(FemaleButton, gridBagConstraints);

        BothButton.setText("Both");
        GenderButtons.add(BothButton);
        BothButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BothButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(BothButton, gridBagConstraints);

        OtherButton.setText("Other");
        GenderButtons.add(OtherButton);
        OtherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(OtherButton, gridBagConstraints);

        NoneButton.setText("None");
        GenderButtons.add(NoneButton);
        NoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(NoneButton, gridBagConstraints);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        getContentPane().add(CancelButton, gridBagConstraints);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 25;
        getContentPane().add(OKButton, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // Add your handling code here:
        menucreate.BlockWindow(false);        
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Add your handling code here:
        
        //System.out.println("Sex is: " + SEXTYPE);
        switch(SEXTYPE)
        {
        case 0: // '\0'
            menucreate.SexName.setText("Male");
            break;

        case 1: // '\001'
            menucreate.SexName.setText("Female");
            break;

        case 2: // '\002'
            menucreate.SexName.setText("Both");
            break;

        case 3: // '\003'
            menucreate.SexName.setText("Other");
            break;

        case 4: // '\004'
            menucreate.SexName.setText("None");
            break;

        default:
            menucreate.SexName.setText("Female");
            break;
        }
        menucreate.RaceButton.setEnabled(true);
        menucreate.MainCharData[0] = new HashMap();
        menucreate.MainCharData[0].put(new Integer(0), new Integer(SEXTYPE));
        menucreate.MainCharData[0].put(new Integer(1), menucreate.SexName.getText());
        menucreate.BlockWindow(false);        
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_OKButtonActionPerformed

    private void NoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneButtonActionPerformed
        // Add your handling code here:
        SEXTYPE = 4;     
        OKButton.setEnabled(true);
    }//GEN-LAST:event_NoneButtonActionPerformed

    private void OtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherButtonActionPerformed
        // Add your handling code here:
        SEXTYPE = 3;        
        OKButton.setEnabled(true);        
    }//GEN-LAST:event_OtherButtonActionPerformed

    private void BothButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BothButtonActionPerformed
        // Add your handling code here:
        SEXTYPE = 2;        
        OKButton.setEnabled(true);        
    }//GEN-LAST:event_BothButtonActionPerformed

    private void FemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleButtonActionPerformed
        // Add your handling code here:
        SEXTYPE = 1;        
        OKButton.setEnabled(true);        
    }//GEN-LAST:event_FemaleButtonActionPerformed

    private void MaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleButtonActionPerformed
        // Add your handling code here:
        SEXTYPE = 0;        
        OKButton.setEnabled(true);        
    }//GEN-LAST:event_MaleButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        menucreate.BlockWindow(false);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitForm

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BothButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JToggleButton FemaleButton;
    private javax.swing.ButtonGroup GenderButtons;
    private javax.swing.JToggleButton MaleButton;
    private javax.swing.JToggleButton NoneButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JToggleButton OtherButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    public int SEXTYPE;
    private CreateMenu menucreate;
}
